### ISSUE TITLE
[Question] node shader setup

### ISSUE THREAD

**Issue by kkartaltepe** [michaeldegroot/cats-blender-plugin#130]
In the shader setup for 2.80 in 8f819dd4deb24063c0a05a1c092ea79d212e9460 specifically a new node tree is added, however in the current branch mmd_tools creates its own shader node tree so the resulting shader tree for materials has TWO material outputs. e.g. https://i.imgur.com/K96jdz7.png

Is this on purpose? Is it possible to revert creating cats material handlers and rely on the mmd_shader?

(sorry I accidentally created this issue with no title or comment ...)

**Comment by Darkblader24** [comment]
This is done on purpose because the principled shader node is the only one being checked upon FBX export. If I don't add this node with the main texture and an output node attached to it, the FBX will have no materials assigned in Unity and you have to manually apply them.
Adding these two nodes does not influence the MMD shader node, since only one output node can be active at any time and the one Cats adds will be the inactive one.

**Comment by kkartaltepe** [comment]
Ah that makes sense, thank you for the prompt answer!

**Comment by kkartaltepe** [comment]
I also noticed, export_fbx_bin.py appears to be GPL licensed, while this project is released under MIT. GPL Licensed code cannot be re-licensed as MIT so it would be best to leave the GPL header in the modified fbx_patch.py

**Comment by Darkblader24** [comment]
Oh, you are right. I will add it 👍
